# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|


  config.vm.box = "centos/7"
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |vb|
   vb.memory = "2048"
  end

  (51..53).each do |i|
    config.vm.define "docker#{i}" do |node|
      node.vm.hostname = "docker#{i}"
      node.vm.network "private_network", ip: "192.168.33.#{i}"
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum clean all
    yum -y install gcc libstdc++-devel gcc-c++ curl-devel libxml2-devel openssl-devel mailcap rsync yum-utils
    curl -fsSL get.docker.com -o get-docker.sh
    bash get-docker.sh
  SHELL
end
